In [2]:
# この10操作を何も見ずに書けるまで繰り返す
df.groupby("col").agg({"val": ["mean", "sum", "count"]}) #1)
df.pivot_table(index="a", columns="b", values="c", aggfunc="sum")

df.merge(df2, on="key", how="left") #2) Merge two columns with using the key as id column, using the whole left as a base

df[df["col"].isin(["a","b"])] #4)only the columns that are "a" or "b"
df.sort_values("col", ascending=False).head(10) #5) new col
df.drop_duplicates(subset=["col"]) #8) Just the first appearance of something

df.assign(new_col=lambda x: x["a"] / x["b"]) # 6) just df['new_col'] = something
df.fillna(df.mean(numeric_only=True)) #7) Data imputation!
df["col"].apply(lambda x: ...) #9)
df.melt(id_vars=["id"], value_vars=["a","b"]) #10) make a super long list of each row being one appearance of a or b

NameError: name 'df' is not defined

In [3]:
# pivot_table = groupby + aggregation + reshape into a matrix-like table

#df.pivot_table(index="a", columns="b", values="c", aggfunc="sum")

import pandas as pd

df = pd.DataFrame({
    "region": ["East", "East", "West", "West", "East"],
    "category": ["A", "B", "A", "B", "A"],
    "sales": [100, 200, 150, 120, 50]
})

df.pivot_table(index="region", columns="category", values="sales", aggfunc="sum")

category    A    B
region
East      150  200
West      150  120

In [4]:
df["col"].apply(func) #Apply this function to each row of the column
df["name"].apply(lambda x: x.upper())
#Common uses of apply

df["city"] = df["city"].apply(lambda x: x.strip().title() if isinstance(x, str) else x) #1) cleaning strings
df["bucket"] = df["score"].apply(
    lambda x: "low" if x < 50 else "medium" if x < 80 else "high"
) #2) custom characterization

df["percent_text"] = df["rate"].apply(lambda x: f"{100*x:.1f}%") # 3) formatting text
top_products = df.groupby("category").apply(lambda g: g.nlargest(5, "rating")) # 4) working group-by-group

KeyError: 'col'

In [ ]:
# Selection / filtering
df.loc[row_condition, ["col1", "col2"]]
df.query("a > 0 and b == 'x'")

# Missing values
df["col"].isna()
df["col"].notna()

# Types / parsing
df["col"] = df["col"].astype("float")
df["date"] = pd.to_datetime(df["date"])

# Counting / uniqueness
df["col"].value_counts(dropna=False)
df["col"].nunique()

# Renaming
df = df.rename(columns={"old_name": "new_name"})

# Group-aware operations
df["group_mean"] = df.groupby("group")["value"].transform("mean")

# Mapping / replacing
df["mapped"] = df["col"].map({"a": 1, "b": 2})
df["col"] = df["col"].replace({"old": "new", "unknown": np.nan})

# String / datetime accessors
df["clean"] = df["text"].str.strip().str.lower()
df["year"] = df["date"].dt.year

# Combining / reshaping
df_all = pd.concat([df1, df2], axis=0, ignore_index=True)
df_long = df.explode("tags")

# Duplicate handling
df.duplicated()
df = df.drop_duplicates(subset=["col"])

# Index management
df = df.set_index("id")
df = df.reset_index()

# Ranking / bounding
df["rank"] = df["score"].rank(method="dense", ascending=False)
df["bounded"] = df["score"].clip(lower=0, upper=100)

# Conditional replacement
df["x_where"] = df["x"].where(df["x"] > 0, other=0)
df["x_mask"] = df["x"].mask(df["x"] < 0, other=0)

In [7]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("pandas_training_database/pandas_training.sqlite")

customers = pd.read_sql("SELECT * FROM customers", conn)
orders = pd.read_sql("SELECT * FROM orders", conn)
order_items = pd.read_sql("SELECT * FROM order_items", conn)
products = pd.read_sql("SELECT * FROM products", conn)

In [8]:
print(customers)

      customer_id first_name  last_name   age gender            city state  \
0               1        Ana  Rodrigues  38.0      M         Goiania    GO
1               2      Tiago     Tanaka  49.0      F         Goiania    GO
2               3      Sofia    Almeida  29.0   None        Campinas    SP
3               4     Rafael      Silva  23.0      M       Fortaleza    CE
4               5    Eduarda    Almeida  34.0  Other    Porto Alegre    RS
...           ...        ...        ...   ...    ...             ...   ...
1215         1216    NICOLAS       Melo  32.0      M        Salvador    BA
1216         1217    JUYOUNG    Almeida  31.0      M  Rio de Janeiro    RJ
1217         1218      JULIA  Rodrigues  44.0   None  Belo Horizonte    MG
1218         1219    EDUARDA    Almeida  31.0  Other       Sao Paulo    SP
1219         1220      PEDRO      Costa  23.0      M       Fortaleza    CE

     signup_date   segment membership_tier preferred_channel  is_active  \
0     2023-08-17  consumer          silver           organic          0
1     2023-06-28  consumer        platinum            direct          1
2     2023-02-24  consumer          silver            social          1
3     2024-07-23  consumer          bronze            social          1
4     2024-07-23  consumer          bronze             email          0
...          ...       ...             ...               ...        ...
1215  2025-02-04  consumer          bronze             email          1
1216  2023-02-02  consumer          bronze            direct          1
1217  2023-10-11  consumer            gold            direct          1
1218  2024-03-31  consumer          bronze             email          1
1219  2023-07-28  consumer        platinum            direct          1

      lifetime_value
0              61.38
1             105.68
2              50.43
3              80.52
4              28.36
...              ...
1215          120.47
1216          102.44
1217          288.26
1218          159.49
1219           64.03

[1220 rows x 13 columns]

In [9]:
from IPython.display import Markdown, display
from pathlib import Path

display(Markdown(Path("pandas_training_database/practice_prompts.md").read_text()))


# ALTERNATIVELY, WE COULD HAVE DONE THE ONE BELOW

#with open("practice_prompts.md", "r", encoding="utf-8") as f:
#    text = f.read()

#display(Markdown(text))

# Practice Prompts

## 1) Inspection / profiling
1. Show the number of rows and columns in each table.
2. Which columns have missing values, and how many?
3. Which columns look like keys? Verify uniqueness with `nunique`.

## 2) Filtering / selection
4. Find active gold or platinum customers from Sao Paulo older than 30.
5. Show orders placed in 2025 that were cancelled or returned.
6. Select products in Electronics and Beauty with rating >= 4.5.

## 3) Sorting / top-k
7. Top 10 customers by lifetime_value.
8. Top 10 products by average rating within each category.

## 4) Groupby / agg
9. Compute revenue by month.
10. Compute average age, customer count, and average lifetime_value by membership_tier.
11. Count orders by status and payment_method.

## 5) Merge / join
12. Join orders with customers and compute order count by city.
13. Join order_items with products and find revenue by category.
14. Join support_tickets with orders to compare ticket volume by order status.

## 6) Assign / transform
15. Add a net_item_revenue column = quantity * unit_price - item_discount.
16. Within each order, compute each item's share of order revenue using `transform`.
17. Compute customer-level total spend and merge it back to customers.

## 7) Pivot / reshape
18. Create a pivot table of revenue by category and order month.
19. Use `monthly_wide_sales` and `melt` to convert wide months into a tidy long table.
20. Build a pivot of ticket count by issue_type and status.

## 8) Missing values / cleaning
21. Fill missing ages with the median age.
22. Fill missing product prices with category-level median prices.
23. Detect duplicate-like customer records with the same name and signup_date.

## 9) Text / list-like columns
24. Split `products.tags` into lists and `explode` them.
25. Count how often each tag appears overall and by category.
26. Standardize customer first names to title case.

## 10) Dates
27. Convert all date columns to datetime.
28. Extract year, month, weekday from orders.
29. Compute days since signup for each customer relative to the latest order date.

## 11) Intermediate case drills
30. Which marketing channel has the highest conversion rate?
31. Do support tickets correlate with lower satisfaction by issue type?
32. Which cities have the highest average order value?
33. Which membership tier generates the most revenue per active customer?

## 12) Harder interview-style drills
34. Find the top 3 products by revenue within each category.
35. Compute 30-day repeat purchase rate by signup cohort month.
36. Build a customer summary table with:
   - total orders
   - total spend
   - average order value
   - days since signup
   - most recent order date
   - whether they ever opened a marketing message

In [10]:
for df in all:
    print(df)
    #print(df.columns)

TypeError: 'builtin_function_or_method' object is not iterable

In [11]:
all = [customers, orders, order_items, products]
#1.1) 
for i in all:
    print(i.shape)


#1.2)
for df in all:
    print(df.isna().any())
    print(df.isna().sum())

#1.3)
for df in all:
    for i in df:
        print(f"{i} is key: {df[i].nunique() == df.shape[0]}")

(1220, 13)
(4200, 10)
(9472, 6)
(180, 11)
customer_id          False
first_name           False
last_name            False
age                   True
gender                True
city                 False
state                False
signup_date          False
segment              False
membership_tier      False
preferred_channel    False
is_active            False
lifetime_value        True
dtype: bool
customer_id            0
first_name             0
last_name              0
age                   36
gender               331
city                   0
state                  0
signup_date            0
segment                0
membership_tier        0
preferred_channel      0
is_active              0
lifetime_value        19
dtype: int64
order_id           False
customer_id        False
order_date         False
status             False
payment_method     False
shipping_fee        True
discount_amount     True
coupon_code         True
ship_city          False
delivery_days       True
dtype: bool
order_id              0
customer_id           0
order_date            0
status                0
payment_method        0
shipping_fee         93
discount_amount     200
coupon_code        2429
ship_city             0
delivery_days       346
dtype: int64
order_item_id    False
order_id         False
product_id       False
quantity         False
unit_price       False
item_discount     True
dtype: bool
order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price         0
item_discount    311
dtype: int64
product_id         False
product_name       False
category           False
subcategory        False
brand              False
price               True
cost               False
rating              True
launch_date        False
tags               False
is_discontinued    False
dtype: bool
product_id         0
product_name       0
category           0
subcategory        0
brand              0
price              4
cost               0
rating             7
launch_date        0
tags               0
is_discontinued    0
dtype: int64
customer_id is key: True
first_name is key: False
last_name is key: False
age is key: False
gender is key: False
city is key: False
state is key: False
signup_date is key: False
segment is key: False
membership_tier is key: False
preferred_channel is key: False
is_active is key: False
lifetime_value is key: False
order_id is key: True
customer_id is key: False
order_date is key: False
status is key: False
payment_method is key: False
shipping_fee is key: False
discount_amount is key: False
coupon_code is key: False
ship_city is key: False
delivery_days is key: False
order_item_id is key: True
order_id is key: False
product_id is key: False
quantity is key: False
unit_price is key: False
item_discount is key: False
product_id is key: True
product_name is key: True
category is key: False
subcategory is key: False
brand is key: False
price is key: False
cost is key: True
rating is key: False
launch_date is key: False
tags is key: False
is_discontinued is key: False

In [12]:
# 2) Filtering / selection
#Find active gold or platinum customers from Sao Paulo older than 30.
#Show orders placed in 2025 that were cancelled or returned.
#Select products in Electronics and Beauty with rating >= 4.5.

#2.4)

#print(customers.columns)
#print(customers[(customers["membership_tier"].isin(["gold", "platinum"])) & (customers["is_active"]) & (customers["age"] >= 30.0)])

#2.5)
#print(orders.columns)
#print(orders.describe)

#orders["order_date"] = pd.to_datetime(orders["order_date"])

#print(orders[(orders['status'].isin(['cancelled', 'returned'])) & (orders['order_date'].dt.year == 2025) ])

#2.6)

print(products[(products['category'].isin(['Electronics', 'Beauty'])) & (products['rating'] >= 4.5) ])

    product_id         product_name     category subcategory   brand   price  \
2            3  Nimbus Smart_Home 3  Electronics  smart_home  Aurora  186.54
6            7      Nimbus Laptop 7  Electronics      laptop   Solis  395.50
9           10     Nimbus Tablet 10  Electronics      tablet    Nova   14.34
14          15       Pine Tablet 15  Electronics      tablet   Cedar  689.92
15          16      Aurora Audio 16  Electronics       audio  Vertex  248.90
16          17     Harbor Laptop 17  Electronics      laptop   Cedar   37.96
28          29      Nimbus Audio 29  Electronics       audio   Lumen  109.38
72          73     Pine Wellness 73       Beauty    wellness   Atlas  331.28
75          76     Aurora Makeup 76       Beauty      makeup   Cedar  675.16
87          88   Vertex Skincare 88       Beauty    skincare  Vertex  266.47

      cost  rating launch_date                               tags  \
2   109.56     4.9  2022-02-08                   recyclable|vegan
6   183.68     4.6  2025-12-31               bulky|limited|budget
9     9.02     4.7  2024-09-18                              vegan
14  282.35     5.0  2025-02-27             portable|organic|bulky
15  119.18     5.0  2024-06-03        budget|portable|editor_pick
16   20.94     4.6  2023-12-01      limited|recyclable|bestseller
28   82.44     5.0  2022-06-02  portable|giftable|premium|organic
72  220.68     5.0  2023-02-27                         new|budget
75  280.42     4.5  2023-12-12      seasonal|wireless|organic|eco
87  220.50     4.8  2023-11-01                        new|fragile

    is_discontinued
2                 0
6                 0
9                 0
14                0
15                0
16                0
28                0
72                0
75                0
87                0

In [13]:
#3) Sorting / top-k
#Top 10 customers by lifetime_value.
#Top 10 products by average rating within each category.
#print(customers.columns)
#customers.sort_values("lifetime_value", ascending = False).head(10)
print(products.columns)
#print(products.groupby(['product_id','category'])['rating'].mean())

a = products.groupby(["category", "product_id"])["rating"].mean()

b = products.groupby(["category", "product_id"])["rating"].mean().reset_index()

c = products.groupby(["category", "product_id"])["rating"].mean().reset_index().sort_values(["category", "rating"], ascending=[True, False])

d = products.groupby(["category", "product_id"])["rating"].mean().reset_index().sort_values(["category", "rating"], ascending=[True, False]).groupby("category")

e = products.groupby(["category", "product_id"])["rating"].mean().reset_index().sort_values(["category", "rating"], ascending=[True, False]).groupby("category").head(10)

print(f"a is {a}")
print(f"b is {b}")
print(f"c is {c}")
print(f"d is {d}")
print(f"e is {e}")

(products
 .groupby(["category", "product_id"])["rating"]
 .mean()
 .reset_index()
 .sort_values(["category", "rating"], ascending=[True, False])
 .groupby("category")
 .head(10)
)

Index(['product_id', 'product_name', 'category', 'subcategory', 'brand',
       'price', 'cost', 'rating', 'launch_date', 'tags', 'is_discontinued'],
      dtype='object')
a is category  product_id
Beauty    61            3.1
          62            4.0
          63            3.8
          64            4.4
          65            4.0
                       ...
Sports    116           4.4
          117           3.8
          118           NaN
          119           3.8
          120           3.6
Name: rating, Length: 180, dtype: float64
b is     category  product_id  rating
0     Beauty          61     3.1
1     Beauty          62     4.0
2     Beauty          63     3.8
3     Beauty          64     4.4
4     Beauty          65     4.0
..       ...         ...     ...
175   Sports         116     4.4
176   Sports         117     3.8
177   Sports         118     NaN
178   Sports         119     3.8
179   Sports         120     3.6

[180 rows x 3 columns]
c is     category  product_id  rating
12    Beauty          73     5.0
27    Beauty          88     4.8
15    Beauty          76     4.5
3     Beauty          64     4.4
18    Beauty          79     4.4
..       ...         ...     ...
156   Sports          97     3.2
163   Sports         104     3.2
171   Sports         112     3.2
157   Sports          98     NaN
177   Sports         118     NaN

[180 rows x 3 columns]
d is <pandas.core.groupby.generic.DataFrameGroupBy object at 0x11b8bac10>
e is         category  product_id  rating
12        Beauty          73     5.0
27        Beauty          88     4.8
15        Beauty          76     4.5
3         Beauty          64     4.4
18        Beauty          79     4.4
20        Beauty          81     4.4
21        Beauty          82     4.4
8         Beauty          69     4.3
10        Beauty          71     4.3
14        Beauty          75     4.2
44   Electronics          15     5.0
45   Electronics          16     5.0
58   Electronics          29     5.0
32   Electronics           3     4.9
39   Electronics          10     4.7
36   Electronics           7     4.6
46   Electronics          17     4.6
50   Electronics          21     4.4
55   Electronics          26     4.3
57   Electronics          28     4.3
65          Food         156     5.0
79          Food         170     4.7
78          Food         169     4.6
86          Food         177     4.6
66          Food         157     4.5
62          Food         153     4.4
70          Food         161     4.3
76          Food         167     4.3
71          Food         162     4.2
75          Food         166     4.2
118         Home          59     5.0
100         Home          41     4.8
111         Home          52     4.8
112         Home          53     4.8
108         Home          49     4.7
96          Home          37     4.6
95          Home          36     4.5
107         Home          48     4.5
109         Home          50     4.5
93          Home          34     4.2
128       Office         129     5.0
141       Office         142     5.0
132       Office         133     4.9
125       Office         126     4.8
126       Office         127     4.8
134       Office         135     4.8
124       Office         125     4.4
147       Office         148     4.3
130       Office         131     4.2
133       Office         134     4.2
161       Sports         102     5.0
166       Sports         107     5.0
170       Sports         111     4.7
174       Sports         115     4.7
158       Sports          99     4.4
167       Sports         108     4.4
175       Sports         116     4.4
162       Sports         103     4.3
159       Sports         100     4.2
173       Sports         114     4.0

        category  product_id  rating
12        Beauty          73     5.0
27        Beauty          88     4.8
15        Beauty          76     4.5
3         Beauty          64     4.4
18        Beauty          79     4.4
20        Beauty          81     4.4
21        Beauty          82     4.4
8         Beauty          69     4.3
10        Beauty          71     4.3
14        Beauty          75     4.2
44   Electronics          15     5.0
45   Electronics          16     5.0
58   Electronics          29     5.0
32   Electronics           3     4.9
39   Electronics          10     4.7
36   Electronics           7     4.6
46   Electronics          17     4.6
50   Electronics          21     4.4
55   Electronics          26     4.3
57   Electronics          28     4.3
65          Food         156     5.0
79          Food         170     4.7
78          Food         169     4.6
86          Food         177     4.6
66          Food         157     4.5
62          Food         153     4.4
70          Food         161     4.3
76          Food         167     4.3
71          Food         162     4.2
75          Food         166     4.2
118         Home          59     5.0
100         Home          41     4.8
111         Home          52     4.8
112         Home          53     4.8
108         Home          49     4.7
96          Home          37     4.6
95          Home          36     4.5
107         Home          48     4.5
109         Home          50     4.5
93          Home          34     4.2
128       Office         129     5.0
141       Office         142     5.0
132       Office         133     4.9
125       Office         126     4.8
126       Office         127     4.8
134       Office         135     4.8
124       Office         125     4.4
147       Office         148     4.3
130       Office         131     4.2
133       Office         134     4.2
161       Sports         102     5.0
166       Sports         107     5.0
170       Sports         111     4.7
174       Sports         115     4.7
158       Sports          99     4.4
167       Sports         108     4.4
175       Sports         116     4.4
162       Sports         103     4.3
159       Sports         100     4.2
173       Sports         114     4.0

In [14]:
#4) Groupby / agg
# 4.9 Compute revenue by month.
# 4.10 Compute average age, customer count, and average lifetime_value by membership_tier.
# 4.11 Count orders by status and payment_method.



print(customer_summary_by_tier.head())

#customers = pd.read_sql("SELECT * FROM customers", conn)
#orders = pd.read_sql("SELECT * FROM orders", conn)
#order_items = pd.read_sql("SELECT * FROM order_items", conn)
#products = pd.read_sql("SELECT * FROM products", conn)

4.9
orders["order_date"] = pd.to_datetime(orders["order_date"])
orders["month"] = orders["order_date"].dt.to_period("M")

revenue_by_month = (
    order_items
    .assign(revenue=order_items["quantity"] * order_items["unit_price"])
    .merge(orders[["order_id", "month"]], on="order_id", how="left")
    .groupby("month")["revenue"]
    .sum()
    .reset_index()
)


# 4.10

customer_summary_by_tier = (
    customers.groupby('membership_tier').agg(avg_age = ("age", "mean"), customer_count = ("customer_id", "count"), avg_lifetime_value = ("lifetime_value", "mean"))
    .reset_index()
)

# 4.11 Count orders by status and payment_method.

order_count = (
    orders.groupby(['status', 'payment_method'])
    .agg(count_status = ('status', 'count'), count_payment_method = ('payment_method', 'count'))
)
# Which is the same as 

orders_by_status_payment = (
    orders.groupby(["status", "payment_method"])
    .size()
    .reset_index(name="order_count")
)

NameError: name 'customer_summary_by_tier' is not defined

In [25]:
#5) Merge / join
# 5.12) Join orders with customers and compute order count by city.
# 5.13) Join order_items with products and find revenue by category.
# 5.14) Join support_tickets with orders to compare ticket volume by order status.

print(orders.columns, customers.columns)

orders
result = pd.merge(orders, customers, on = "customer_id", how = "inner")



result.groupby("ship_city")["order_id"].count()
#result = pd.merge(df1, df2, on="id", how="inner")
#how="inner" → matching keys only
#how="left" → all rows from left table
#how="right" → all rows from right table
#how="outer" → all rows from both tables

print(order_items.columns, products.columns)
merge = pd.merge(order_items, products, on = "product_id", how = "inner")
merge["revenue"] = merge["quantity"]*merge["unit_price"]
revenue_by_category = (
    merge.groupby("category")["revenue"].sum().reset_index(name="product_id")
)
print(revenue_by_category)

Index(['order_id', 'customer_id', 'order_date', 'status', 'payment_method',
       'shipping_fee', 'discount_amount', 'coupon_code', 'ship_city',
       'delivery_days'],
      dtype='object') Index(['customer_id', 'first_name', 'last_name', 'age', 'gender', 'city',
       'state', 'signup_date', 'segment', 'membership_tier',
       'preferred_channel', 'is_active', 'lifetime_value'],
      dtype='object')
Index(['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price',
       'item_discount'],
      dtype='object') Index(['product_id', 'product_name', 'category', 'subcategory', 'brand',
       'price', 'cost', 'rating', 'launch_date', 'tags', 'is_discontinued'],
      dtype='object')
      category  product_id
0       Beauty   614674.15
1  Electronics   577250.49
2         Food   688820.21
3         Home   622224.28
4       Office   605557.76
5       Sports   622578.02

In [32]:
print(orders.columns, customers.columns)
print(order_items.columns, products.columns)

Index(['order_id', 'customer_id', 'order_date', 'status', 'payment_method',
       'shipping_fee', 'discount_amount', 'coupon_code', 'ship_city',
       'delivery_days'],
      dtype='object') Index(['customer_id', 'first_name', 'last_name', 'age', 'gender', 'city',
       'state', 'signup_date', 'segment', 'membership_tier',
       'preferred_channel', 'is_active', 'lifetime_value'],
      dtype='object')
Index(['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price',
       'item_discount', 'net_item_revenue_column', 'share_of_order_revenue'],
      dtype='object') Index(['product_id', 'product_name', 'category', 'subcategory', 'brand',
       'price', 'cost', 'rating', 'launch_date', 'tags', 'is_discontinued'],
      dtype='object')

In [35]:
#6) Assign / transform
# 6.15)Add a net_item_revenue column = quantity * unit_price - item_discount.
# 6.16) Within each order, compute each item's share of order revenue using transform.
# 6.17) Compute customer-level total spend and merge it back to customers.
order_items = order_items.assign(net_item_revenue_column =order_items["quantity"]*order_items["unit_price"] - order_items["item_discount"])
print(order_items)

order_items["share_of_order_revenue"] =  order_items["net_item_revenue_column"]/order_items.groupby("order_id")["net_item_revenue_column"].transform("sum")
print(order_items["share_of_order_revenue"])

"""
all_order_details = pd.merge(order_items, orders, on = "product_id", how = "left")
all_order_details = pd.merge(all_order_details, customers, on = "product_id", how = "left")
total_spend = all_order_details.groupby("customer_id")["net_item_revenue"].transform("sum")
print(total_spend)
"""

all_order_details = pd.merge(order_items, orders, on="order_id", how="left")
customer_spend = (
    all_order_details.groupby("customer_id", as_index=False)["net_item_revenue_column"]
    .sum()
    .rename(columns={"net_item_revenue_column": "total_spend"})
)

customers = pd.merge(customers, customer_spend, on="customer_id", how="left")
print(customers)

      order_item_id  order_id  product_id  quantity  unit_price  \
0                 1         1          61         3      363.53
1                 2         1         125         1      459.95
2                 3         2         178         3      361.66
3                 4         2          67         2       51.07
4                 5         2          78         1       39.06
...             ...       ...         ...       ...         ...
9467           9468      4197          59         1      151.49
9468           9469      4197           4         1      652.47
9469           9470      4198         142         1      543.02
9470           9471      4199          19         3      164.08
9471           9472      4200          76         2      671.08

      item_discount  net_item_revenue_column  share_of_order_revenue
0              0.00                  1090.59                0.703361
1              0.00                   459.95                0.296639
2              0.00                  1084.98                0.890518
3              4.20                    97.94                0.080386
4              3.61                    35.45                0.029096
...             ...                      ...                     ...
9467           0.45                   151.04                0.188852
9468           3.73                   648.74                0.811148
9469           1.29                   541.73                1.000000
9470           0.00                   492.24                1.000000
9471           5.37                  1336.79                1.000000

[9472 rows x 8 columns]
0       0.703361
1       0.296639
2       0.890518
3       0.080386
4       0.029096
          ...
9467    0.188852
9468    0.811148
9469    1.000000
9470    1.000000
9471    1.000000
Name: share_of_order_revenue, Length: 9472, dtype: float64
      customer_id first_name  last_name   age gender            city state  \
0               1        Ana  Rodrigues  38.0      M         Goiania    GO
1               2      Tiago     Tanaka  49.0      F         Goiania    GO
2               3      Sofia    Almeida  29.0   None        Campinas    SP
3               4     Rafael      Silva  23.0      M       Fortaleza    CE
4               5    Eduarda    Almeida  34.0  Other    Porto Alegre    RS
...           ...        ...        ...   ...    ...             ...   ...
1215         1216    NICOLAS       Melo  32.0      M        Salvador    BA
1216         1217    JUYOUNG    Almeida  31.0      M  Rio de Janeiro    RJ
1217         1218      JULIA  Rodrigues  44.0   None  Belo Horizonte    MG
1218         1219    EDUARDA    Almeida  31.0  Other       Sao Paulo    SP
1219         1220      PEDRO      Costa  23.0      M       Fortaleza    CE

     signup_date   segment membership_tier preferred_channel  is_active  \
0     2023-08-17  consumer          silver           organic          0
1     2023-06-28  consumer        platinum            direct          1
2     2023-02-24  consumer          silver            social          1
3     2024-07-23  consumer          bronze            social          1
4     2024-07-23  consumer          bronze             email          0
...          ...       ...             ...               ...        ...
1215  2025-02-04  consumer          bronze             email          1
1216  2023-02-02  consumer          bronze            direct          1
1217  2023-10-11  consumer            gold            direct          1
1218  2024-03-31  consumer          bronze             email          1
1219  2023-07-28  consumer        platinum            direct          1

      lifetime_value  total_spend
0              61.38       567.52
1             105.68      3718.12
2              50.43      1460.44
3              80.52      1571.38
4              28.36      1485.45
...              ...          ...
1215          120.47          NaN
1216          102.44          NaN
1217          288.26          NaN
1218          159.49          NaN
1219           64.03          NaN

[1220 rows x 14 columns]

In [48]:
#7) Pivot / reshape
# 7.18 Create a pivot table of revenue by category and order month.
# 7.19 Use monthly_wide_sales and melt to convert wide months into a tidy long table.
# 7.20 Build a pivot of ticket count by issue_type and status.

#df.pivot_table(index="a", columns="b", values="c", aggfunc="sum")

# make sure order_date is datetime
all_order_details = pd.merge(order_items, orders, on="order_id", how="left")
all_order_details = pd.merge(all_order_details, products, on="product_id", how="left")
all_order_details = pd.merge(all_order_details, customers, on="customer_id", how="left")

all_order_details["order_date"] = pd.to_datetime(all_order_details["order_date"])

# create order month
all_order_details["order_month"] = all_order_details["order_date"].dt.to_period("M").astype(str)

revenue_by_category_month = pd.pivot_table(
    all_order_details,
    index="category",
    columns="order_month",
    values="net_item_revenue_column",
    aggfunc="sum",
    fill_value=0
)

print(revenue_by_category_month)

monthly_wide_sales = pd.read_csv("pandas_training_database/monthly_wide_sales.csv")
support_tickets = pd.read_csv("pandas_training_database/support_tickets.csv")


monthly_long_sales = monthly_wide_sales.melt(
    id_vars="metric",
    var_name="order_month",
    value_name="value"
)

print(monthly_long_sales)
ticket_count_pivot = pd.pivot_table(
    support_tickets,
    index="issue_type",
    columns="status",
    values="ticket_id",
    aggfunc="count",
    fill_value=0
)

print(ticket_count_pivot)

order_month   2024-01   2024-02   2024-03   2024-04   2024-05   2024-06  \
category
Beauty       27163.55  16054.72  21817.32  21510.37  24478.04  20376.25
Electronics  27735.15  26621.03  26802.93  21445.66  16224.56  27425.21
Food         20524.15  25108.69  21793.65  26290.33  28625.37  24506.34
Home         18590.29  19634.52  19936.05  21640.16  22967.57  33987.44
Office       20364.14  21637.75  18912.77  24960.31  28617.69  20342.05
Sports       22108.02  21932.36  22748.29  20187.09  21427.99  25527.24

order_month   2024-07   2024-08   2024-09   2024-10  ...   2025-05   2025-06  \
category                                             ...
Beauty       21960.95  22110.72  23516.52  27775.97  ...  21797.86  20370.33
Electronics  16940.81  21734.87  26689.27  12780.52  ...  20345.57  11128.54
Food         33688.50  24536.10  26029.88  19896.99  ...  21338.24  22078.13
Home         18776.53  19143.06  26193.79  21907.76  ...  19899.79  20700.80
Office       21912.13  24354.56  26125.74  19911.97  ...  18180.42  14686.42
Sports       26324.92  26688.45  23767.66  18229.46  ...  25532.49  23036.92

order_month   2025-07   2025-08   2025-09   2025-10   2025-11   2025-12  \
category
Beauty       20071.00  25744.28  18992.92  25296.20  18489.89  18775.35
Electronics  21452.80  22159.12  15240.57  26321.57  15740.16  20462.02
Food         33433.48  23383.87  26986.35  25996.17  26582.32  23318.89
Home         27941.71  23708.89  21745.83  27699.33  20696.53  27817.31
Office       17920.85  16739.80  20115.87  24825.45  21927.82  28885.11
Sports       16656.33  20400.88  18317.97  27232.86  21414.88  20540.54

order_month   2026-01   2026-02
category
Beauty       22946.64  18583.92
Electronics  28144.10  13999.21
Food         22631.49  16345.90
Home         21763.69  10623.19
Office       21277.40  19331.48
Sports       25255.60  19572.40

[6 rows x 26 columns]
             metric order_month      value
0           revenue     2025-03  149261.61
1            orders     2025-03     166.00
2   avg_order_value     2025-03     899.17
3           revenue     2025-04  151179.85
4            orders     2025-04     180.00
5   avg_order_value     2025-04     839.89
6           revenue     2025-05  132023.97
7            orders     2025-05     154.00
8   avg_order_value     2025-05     857.30
9           revenue     2025-06  114821.39
10           orders     2025-06     137.00
11  avg_order_value     2025-06     838.11
12          revenue     2025-07  140475.80
13           orders     2025-07     161.00
14  avg_order_value     2025-07     872.52
15          revenue     2025-08  137050.48
16           orders     2025-08     166.00
17  avg_order_value     2025-08     825.61
18          revenue     2025-09  123195.60
19           orders     2025-09     140.00
20  avg_order_value     2025-09     879.97
21          revenue     2025-10  161125.81
22           orders     2025-10     171.00
23  avg_order_value     2025-10     942.26
24          revenue     2025-11  127713.01
25           orders     2025-11     151.00
26  avg_order_value     2025-11     845.78
27          revenue     2025-12  145154.36
28           orders     2025-12     167.00
29  avg_order_value     2025-12     869.19
30          revenue     2026-01  147046.37
31           orders     2026-01     182.00
32  avg_order_value     2026-01     807.95
33          revenue     2026-02  102833.00
34           orders     2026-02     118.00
35  avg_order_value     2026-02     871.47
status            closed  open  pending
issue_type
account_problem      219    24       48
damaged_item         215    30       42
delivery_issue       216    25       60
payment_issue        249    29       48
product_question     249    22       44
refund_request       213    20       47

,metric,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12,2026-01,2026-02
0,revenue,149261.61,151179.85,132023.97,114821.39,140475.80,137050.48,123195.60,161125.81,127713.01,145154.36,147046.37,102833.00
1,orders,166.00,180.00,154.00,137.00,161.00,166.00,140.00,171.00,151.00,167.00,182.00,118.00
2,avg_order_value,899.17,839.89,857.30,838.11,872.52,825.61,879.97,942.26,845.78,869.19,807.95,871.47